### ISSUE TITLE
OpenGL ES 3.2, Vulkan and OpenCL support

### ISSUE THREAD

**Issue by oi3d** [tareksander/termux-gui-c-bindings#19]
Hello. My hardware supports OpenGL ES 3.2 Compute Shaders, Vulkan and OpenCL. 
Can I use **termux-gui-c-bindings** and call into these APIs?

I am specifically interested in OpenGL ES 3.2 at the moment
In "tutorial/c/buffer_gl.c" I have seen #include <GLES2/gl2.h> being used.
Is anything stopping me from using
#include <GLES3/gl32.h>
?
Thanks!

P.S. I also use GLFW library in my code. But I assume it have no use in termux-gui?

**Comment by tareksander** [comment]
You can use any GLES and Vulkan version you want, as long as the extensions to import HardwareBuffer memory are present (be sure to link against the system libraries instead of the Mesa ones in Termux). And yes, GLFW is not usable.
