### ISSUE TITLE
Could not connect to socket: No such file or directory error ! termux-am-socket not receiving the broadcast!!

### ISSUE THREAD

**Issue by TdX631** [tareksander/termux-gui-c-bindings#4]
![IMG_20230513_073958](https://github.com/tareksander/termux-gui-c-bindings/assets/132931929/e81effdd-2247-4fb7-9e85-2c6459752c21)
CMake builds, make everything nice, but never connects to tcp🙂

**Comment by tareksander** [comment]
Do you have the Termux:GUI app installed?

**Comment by TdX631** [comment]
yes, working well with python , facing trouble in c/c++ binding.

**Comment by tareksander** [comment]
Do you have the `am-socket` server enabled?  The only way I can reproduce your error is by disabling the socket server and manually overriding the env variable to say that it's enabled. But I'll fix the fallback to regular `am` anyways.

**Comment by tareksander** [comment]
Fixed it now, if you compiled from source, you can pull the repo again. If you use the package, wait for the auto-update to update the package.

**Comment by TdX631** [comment]
hey thanks @tareksander, now it's working fine.
