### ISSUE TITLE
Could not connect to socket

### ISSUE THREAD

**Issue by ghost** [tareksander/termux-gui-c-bindings#5]
when i try to run some example i get the error: Could not connect to socket.
And if i try to run an example that uses opengl i get: eglInitialize: 0x3001

**Comment by tareksander** [comment]
> when i try to run some example i get the error: Could not connect to socket.

See #4.


> And if i try to run an example that uses opengl i get: eglInitialize: 0x3001

If you have the libglvnd package installed (is installed automatically with mesa), use `LD_PRELOAD='/system/lib/:/system/lib64/` to run the GL example, otherwise it'll try to use mesa EGL.
