### ISSUE TITLE
am timeout too short (Android 12 Teclast M40)

### ISSUE THREAD

**Issue by broadblues** [tareksander/termux-gui-c-bindings#9]
I've just been making my first test programs with the C API .

Initially installing via  the dpkg archive  I found the  connection kept failing with errr = 6 (TGUI_ERR_EXCEPTION).

I rebuilt from latest github source and got the same issue. 

After some brute force debugging with printfs I determined the exception was coming from the second timeout  in Connection::Connection. 

For some reason "termux-am" doesn't work on either of my android devices (Android 12 issue?) so it was falling through to "am" but am is slow to respond. 5 seconds is too short a timeout on my system after I upped the second timeout to 10 times the value (overkill :-) A crude connect and quit immediately test times at about 12 seconds. 

I understand that termux-am, when working, is supposed to be faster, so maybe 5 secs is suitable there but I would suggest the timeout for "am" could be upped to 10s for more consistent results.

**Comment by tareksander** [comment]
`termux-am` should always work in theory where this library is used (as you currently need GitHub Actions builds of Termux, where it's already implemented), so I think the priority would be investigating why it doesn't work for you. The am server should be enabled by default. Android 12 should have nothing to do with it. Regardless I have now increased the timeout to 15 seconds, that should cover all users.

**Comment by broadblues** [comment]
Thanks for addressing this.
